version: '3.5'
services:
  database:
    image: mysql:8.0
    container_name: "magazine_db"
    env_file:
      - .env.local
    ports:
      - "33061:3306"

  backend:
    container_name: "magazine_backend"
    env_file:
      - .env.local
    build:
      context: ./
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - database
    command: sh run.sh
    volumes:
      - ./:/app

